_: [
  # Public static pages
  # keep-sorted start
  "_default_http"
  "_default_https"
  "api.lantian.pub"
  "autoconfig.moliy.site"
  "autoconfig.zhyi.cc"
  "autoconfig.zhyi.xin"
  "avatar.lantian.pub"
  "element.lantian.pub"
  "gemini.lantian.pub"
  "google-ssl.zhyi.xin"
  "google-test-ssl.zhyi.xin"
  "gopher.lantian.pub"
  "lab.lantian.pub"
  "lab.xuyh0120.win"
  "zhyi.dn42"
  "lantian.neo"
  "lantian.pub"
  "letsencrypt-ssl.zhyi.xin"
  "letsencrypt-test-ssl.zhyi.xin"
  "ltn.pw"
  "posts.lantian.pub"
  "sip.lantian.pub"
  "stage1.whois.local"
  "stage2.whois.local"
  "tools.lantian.pub"
  "whois.lantian.pub"
  "www.lantian.pub"
  "www.ltn.pw"
  "xn--gmqs02au1c935d.pub"
  "xuyh0120.win"
  "zerossl.zhyi.xin"
  # keep-sorted end

  # Has own authentication system
  # keep-sorted start
  "ai-api.xuyh0120.win"
  "ai.xuyh0120.win"
  "attic.colocrossing.xuyh0120.win"
  "attic.xuyh0120.win"
  "attic.zhyi.xin"
  "bitwarden.xuyh0120.win"
  "cal.zhyi.xin"
  "cal.xuyh0120.win"
  "comments.lantian.pub"
  "dashboard.xuyh0120.win"
  "git.lantian.pub"
  "git.zhyi.xin"
  "hydra.lantian.pub"
  "hydra.zhyi.cc"
  "id.lantian.pub"
  "id.zhyi.xin"
  "immich.xuyh0120.win"
  "jellyfin.xuyh0120.win"
  "lemmy.lantian.pub"
  "login.lantian.pub"
  "login.zhyi.xin"
  "matrix-client.lantian.pub"
  "matrix-client.zhyi.xin"
  "matrix-federation.lantian.pub"
  "matrix-federation.zhyi.xin"
  "n8n.xuyh0120.win"
  "pb.ltn.pw"
  "stats.xuyh0120.win"
  # keep-sorted end

  # Intentionally public without authentication
  # keep-sorted start
  "flapalerted.lantian.pub"
  "lg.zhyi.dn42"
  "lg.lantian.pub"
  "sub.zhyi.cc"
  "tw.zhyi.cc"
  # keep-sorted end
]
