_: [
  # Public static pages
  # keep-sorted start
  "_default_http"
  "_default_https"
  "api.zhyi.xin"
  "autoconfig.zhyi.xin"
  "avatar.zhyi.xin"
  "element.zhyi.xin"
  "gemini.zhyi.xin"
  "google-ssl.zhyi.xin"
  "gopher.zhyi.xin"
  "lab.zhyi.xin"
  "letsencrypt-ssl.zhyi.xin"
  "letsencrypt-test-ssl.zhyi.xin"
  "sip.zhyi.xin"
  "stage1.whois.local"
  "stage2.whois.local"
  "tools.zhyi.xin"
  "whois.zhyi.xin"
  "www.zhyi.xin"
  "xn--gmqs02au1c935d.pub"
  "zerossl.zhyi.xin"
  "zhyi.dn42"
  "zhyi.xin"
  # keep-sorted end

  # Has own authentication system
  # keep-sorted start
  "ai-api.zhyi.xin"
  "ai.zhyi.xin"
  "alert.zhyi.xin"
  "at.zhyi.xin"
  "attic.zhyi.xin"
  "bitwarden.zhyi.xin"
  "cal.zhyi.xin"
  "cloud.zhyi.xin"
  "couchdb.zhyi.xin"
  "dashboard.zhyi.xin"
  "git.zhyi.xin"
  "ha.zhyi.xin"
  "hydra.zhyi.xin"
  "id.zhyi.xin"
  "immich.zhyi.xin"
  "jellyfin.zhyi.xin"
  "lemmy.zhyi.xin"
  "login.zhyi.xin"
  "matrix-client.zhyi.xin"
  "matrix-federation.zhyi.xin"
  "memos.zhyi.xin"
  "n8n.zhyi.xin"
  "nav.zhyi.xin"
  "pb.zhyi.xin"
  "prometheus.zhyi.xin"
  "qnap.zhyi.xin"
  "radicle.zhyi.xin"
  "rk-jellyfin.zhyi.xin"
  "s3.zhyi.xin"
  "stats.zhyi.xin"
  "vaults3.zhyi.xin"
  "wallos.zhyi.xin"
  # keep-sorted end

  # Intentionally public without authentication
  # keep-sorted start
  "flapalerted.zhyi.xin"
  "google.zhyi.xin"
  "greencloud-jp.zhyi.xin"
  "greencloud.zhyi.xin"
  "hostdare.zhyi.xin"
  "lg.zhyi.dn42"
  "lg.zhyi.xin"
  "sub.zhyi.xin"
  "tencent.zhyi.xin"
  "volcengine.zhyi.xin"
  # keep-sorted end
]
