# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }:
{
  imports = [
    ../../nixos/hardware/disable-watchdog.nix
    ../../nixos/hardware/qemu.nix
    ../../nixos/hardware/qemu-hotplug.nix
  ];

  boot.initrd.kernelModules = [ "virtiofs" ];

  boot.loader.grub.device = "/dev/sda";

  fileSystems."/nix" = {
    device = "virtiofs-nixos-home-vm";
    fsType = "virtiofs";
  };

  fileSystems."/mnt/storage" = {
    device = "192.168.0.40:/nixos";
    fsType = "nfs";
    options = [
      "_netdev"
      "noatime"
      "hard"
      "vers=4.1"
      "nconnect=16"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/f20fc9ec-6a17-440a-b4d9-c1af50a1cf37";
    fsType = "ext4";
  };

  services.qemuGuest.enable = true;
}
