# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.loader.grub.device = "/dev/sda";

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # 作者这套 impermanence 配置会把 / 变成 tmpfs。
  # 因此真正持久的系统数据需要放在 /nix，/boot 也必须单独持久化。
  #
  # 下面按强机器 VM 的目标布局写：
  #   /dev/sda1 -> /boot, ext4
  #   /dev/sda2 -> /nix, btrfs
  #
  # 如果实际分区号或 UUID 不同，用 `lsblk -f` 查出来后改这里。
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/f20fc9ec-6a17-440a-b4d9-c1af50a1cf37";
    fsType = "ext4";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/27fc1cd5-3620-4587-85c5-75f53a6e02c3";
    fsType = "btrfs";
    neededForBoot = true;
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
