# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, ... }:

{
  imports = [ ];

  boot.loader.grub.device = "/dev/sda";

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "ahci" "xhci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # 作者这套 impermanence 配置会把 / 变成 tmpfs。
  # 因此真正持久的系统数据需要放在 /nix，/boot 也必须单独持久化。
  #
  # 下面按强机器 VM 的目标布局写：
  #   /dev/sda1 -> /boot, ext4
  #   /dev/sda2 -> /nix, btrfs
  #
  # 如果实际分区号或 UUID 不同，用 `lsblk -f` 查出来后改这里。
  fileSystems."/boot" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };

  fileSystems."/nix" = {
    device = "/dev/sda2";
    fsType = "btrfs";
    options = [
      "compress-force=zstd"
      "autodefrag"
      "nosuid"
      "nodev"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
