{
  inputs,
  config,
  lib,
  LT,
  pkgs,
  ...
}:
let
  mlHomePublicServices = [
    "asf.zhyi.xin"
    "books.zhyi.xin"
    "filebox.zhyi.xin"
    "immich.zhyi.xin"
    "index-helper.zhyi.xin"
    "index.zhyi.xin"
    "jellyfin.zhyi.xin"
    "tachidesk.zhyi.xin"
  ];
  mlHomeOAuthServices = [
    "asf.zhyi.xin"
    "index-helper.zhyi.xin"
    "index.zhyi.xin"
  ];
  mlHomeBasicAuthServices = [
    "books.zhyi.xin"
    "tachidesk.zhyi.xin"
  ];
in
{
  imports = [
    ../../nixos/server.nix

    ./hardware-configuration.nix

    ../../nixos/optional-apps/acme
    ../../nixos/optional-apps/axonhub.nix
    ../../nixos/optional-apps/bepasty.nix
    ../../nixos/optional-apps/bird-lg-go.nix
    ../../nixos/optional-apps/byparr.nix
    ../../nixos/optional-apps/flapalerted.nix
    ../../nixos/optional-apps/grafana.nix
    ../../nixos/optional-apps/gitea
    ../../nixos/optional-apps/gitea-actions.nix
    ../../nixos/optional-apps/imapfilter.nix
    ../../nixos/optional-apps/lemmy.nix
    ../../nixos/optional-apps/maddy.nix
    ../../nixos/optional-apps/matrix-synapse
    ../../nixos/optional-apps/metapi.nix
    ../../nixos/optional-apps/miniflux.nix
    ../../nixos/optional-apps/n8n
    ../../nixos/optional-apps/netbox.nix
    ../../nixos/optional-apps/open-webui
    ../../nixos/optional-apps/plausible.nix
    ../../nixos/optional-apps/prometheus
    ../../nixos/optional-apps/pyison
    ../../nixos/optional-apps/quassel.nix
    ../../nixos/optional-apps/radicale.nix
    ../../nixos/optional-apps/rsshub.nix
    ../../nixos/optional-apps/rsync-server-ci.nix
    ../../nixos/optional-apps/syncthing
    ../../nixos/optional-apps/tg-bot-cleaner-bot
    ../../nixos/optional-apps/yggdrasil-alfis.nix
    ../../nixos/optional-apps/zerotierone-controller.nix

    ../../nixos/optional-cron-jobs/cleanup-github-notifications
    ../../nixos/optional-cron-jobs/dn42-certificate.nix
    ../../nixos/optional-cron-jobs/radicale-calendar-sync.nix
    ../../nixos/optional-cron-jobs/testssl.nix

    "${inputs.secrets}/nixos-hidden-module/11116c7374949a7a"
    "${inputs.secrets}/nixos-hidden-module/35c68fea6f2bde77"
    "${inputs.secrets}/nixos-hidden-module/c9f6c0c333e73062"
    "${inputs.secrets}/nixos-hidden-module/ca877276fe06bd79"
  ];

  networking.domain = lib.mkForce "zhyi.xin";

  systemd.network.networks.eth0 = {
    matchConfig.Name = "eth0";
    address = [
      "203.55.176.158/25"
      "2a11:8083:11:191b::a/64"
    ];
    routes = [
      {
        routeConfig = {
          Destination = "0.0.0.0/0";
          Gateway = "203.55.176.254";
        };
      }
      {
        routeConfig = {
          Destination = "::/0";
          Gateway = "2a11:8083:11::1";
          GatewayOnLink = true;
        };
      }
    ];
    networkConfig.IPv6AcceptRA = "no";
  };

  networking.nameservers = [
    "8.8.8.8"
    "8.8.4.4"
    "1.1.1.1"
    "2001:4860:4860::8888"
    "2001:4860:4860::8844"
  ];

  # Bootstrap files normally generated by the private ltnet-scripts pipeline.
  # The primary sync server owns these paths; generated content can replace them later.
  systemd.tmpfiles.settings.ltnet-scripts = {
    "/nix/sync-servers/ltnet-scripts/pdns-recursor-conf".d = {
      mode = "0755";
      user = "root";
      group = "root";
    };
    "/nix/sync-servers/ltnet-scripts/pdns-recursor-conf/fwd-dn42-interconnect.lua".f = {
      mode = "0644";
      user = "root";
      group = "root";
    };
    "/nix/sync-servers/ltnet-scripts/pdns-recursor-conf/fwd-dn42-interconnect.yml".f = {
      mode = "0644";
      user = "root";
      group = "root";
    };
  };

  lantian.nginxVhosts =
    lib.genAttrs mlHomePublicServices (serverName: {
      locations."/" = {
        proxyPass = "https://${LT.hosts.ml-home-vm.ltnet.IPv4}:${LT.portStr.HTTPS}";
        proxyWebsockets = true;
        proxyNoTimeout = true;
        enableOAuth = builtins.elem serverName mlHomeOAuthServices;
        enableBasicAuth = builtins.elem serverName mlHomeBasicAuthServices;
        extraConfig = ''
          proxy_ssl_name ${serverName};
          proxy_ssl_server_name on;
        '';
      };
      sslCertificate = "lets-encrypt-zhyi.xin";
      noIndex.enable = true;
    })
    // {
      "colocrossing.zhyi.cc".sslCertificate = "lets-encrypt-zhyi.cc";

      "sub.zhyi.cc" = {
        locations = {
          "/" = {
            proxyPass = "https://${LT.hosts.ml-home-vm.ltnet.IPv4}:${LT.portStr.HTTPS}";
            enableOAuth = true;
            extraConfig = ''
              proxy_ssl_name sub.zhyi.cc;
              proxy_ssl_server_name on;
            '';
          };
          "= /mihomo.yaml" = {
            proxyPass = "https://${LT.hosts.ml-home-vm.ltnet.IPv4}:${LT.portStr.HTTPS}";
            extraConfig = ''
              proxy_ssl_name sub.zhyi.cc;
              proxy_ssl_server_name on;
            '';
          };
        };
        sslCertificate = "lets-encrypt-zhyi.cc";
        noIndex.enable = true;
      };
    };

  virtualisation.oci-containers.containers.byparr.ports = [
    "${LT.this.ltnet.IPv4}:${LT.portStr.FlareSolverr}:8191"
  ];
  systemd.services.flaresolverr = lib.mkIf config.services.flaresolverr.enable {
    environment.HOST = lib.mkForce LT.this.ltnet.IPv4;
  };

  # Keep the author's account automation units available, but leave them
  # dormant until this deployment has its own account-specific configuration.
  systemd.services.email-oauth2-proxy.unitConfig.ConditionPathExists =
    "${inputs.secrets}/imapfilter/emailproxy.config";
  systemd.services.imapfilter-outlook.unitConfig.ConditionPathExists =
    "${inputs.secrets}/imapfilter/outlook.lua";
  systemd.services.imapfilter-gmail.unitConfig.ConditionPathExists =
    "${inputs.secrets}/imapfilter/gmail.lua";
  systemd.services.imapfilter-lantian.unitConfig.ConditionPathExists =
    "${inputs.secrets}/imapfilter/lantian.lua";

  systemd.services.tg-bot-cleaner-bot.serviceConfig.ExecCondition = [
    "${pkgs.gnugrep}/bin/grep -qE ^TG_API_ID=.+$ ${config.sops.secrets.tg-bot-cleaner-bot.path}"
    "${pkgs.gnugrep}/bin/grep -qE ^TG_API_HASH=.+$ ${config.sops.secrets.tg-bot-cleaner-bot.path}"
  ];
  systemd.services.cleanup-github-notifications.serviceConfig.ExecCondition =
    "${pkgs.gnugrep}/bin/grep -qE ^GITHUB_TOKEN=.+$ ${config.sops.secrets.cleanup-github-notifications-env.path}";
}
