{
  inputs,
  config,
  lib,
  LT,
  pkgs,
  ...
}:
{
  imports = [
    ../../nixos/server.nix

    ./hardware-configuration.nix
    ./ddns-gcore.nix
    ./home-lan-vhosts.nix

    ../../nixos/optional-apps/acme
    ../../nixos/optional-apps/attic.nix
    ../../nixos/optional-apps/bepasty.nix
    ../../nixos/optional-apps/bird-lg-go.nix
    ../../nixos/optional-apps/byparr.nix
    ../../nixos/optional-apps/dex.nix
    ../../nixos/optional-apps/flapalerted.nix
    ../../nixos/optional-apps/gitea
    ../../nixos/optional-apps/gitea-actions.nix
    ../../nixos/optional-apps/glauth.nix
    ../../nixos/optional-apps/imapfilter.nix
    ../../nixos/optional-apps/lemmy.nix
    ../../nixos/optional-apps/maddy.nix
    ../../nixos/optional-apps/matrix-synapse
    ../../nixos/optional-apps/miniflux.nix
    ../../nixos/optional-apps/netbox.nix
    ../../nixos/optional-apps/plausible.nix
    ../../nixos/optional-apps/pocket-id.nix
    ../../nixos/optional-apps/pyison
    ../../nixos/optional-apps/quassel.nix
    ../../nixos/optional-apps/radicale.nix
    ../../nixos/optional-apps/rsshub.nix
    ../../nixos/optional-apps/rsync-server-ci.nix
    ../../nixos/optional-apps/syncthing
    ../../nixos/optional-apps/tg-bot-cleaner-bot
    ../../nixos/optional-apps/waline
    ../../nixos/optional-apps/yggdrasil-alfis.nix
    ../../nixos/optional-apps/zerotierone-controller.nix

    ../../nixos/optional-cron-jobs/cleanup-github-notifications
    ../../nixos/optional-cron-jobs/dn42-certificate.nix
    ../../nixos/optional-cron-jobs/radicale-calendar-sync.nix
    ../../nixos/optional-cron-jobs/testssl.nix

    "${inputs.secrets}/nixos-hidden-module/11116c7374949a7a"
    "${inputs.secrets}/nixos-hidden-module/35c68fea6f2bde77"
    "${inputs.secrets}/nixos-hidden-module/c9f6c0c333e73062"
    "${inputs.secrets}/nixos-hidden-module/ca877276fe06bd79"
  ];

  systemd.network.networks.ens18 = {
    address = [ "${LT.this.interconnect.IPv4}/24" ];
    gateway = [ "192.168.2.2" ];
    matchConfig.Name = "ens18";
    networkConfig.IPv6AcceptRA = "yes";
    ipv6AcceptRAConfig.DHCPv6Client = "no";
  };

  networking.hosts.${LT.this.interconnect.IPv4} = [ "vaults3.zhyi.cc" ];

  # Keep the manually forwarded UDP 9994 bound to the dedicated controller.
  # The regular client would otherwise claim that public port through UPnP.
  services.zerotierone.localConf.settings.portMappingEnabled = lib.mkForce false;

  # Bootstrap files normally generated by the private ltnet-scripts pipeline.
  # The primary sync server owns these paths; generated content can replace them later.
  systemd.tmpfiles.settings.ltnet-scripts = {
    "/nix/sync-servers/ltnet-scripts/pdns-recursor-conf".d = {
      mode = "0755";
      user = "root";
      group = "root";
    };
    "/nix/sync-servers/ltnet-scripts/pdns-recursor-conf/fwd-dn42-interconnect.lua".f = {
      mode = "0644";
      user = "root";
      group = "root";
    };
    "/nix/sync-servers/ltnet-scripts/pdns-recursor-conf/fwd-dn42-interconnect.yml".f = {
      mode = "0644";
      user = "root";
      group = "root";
    };
  };

  lantian.nginxVhosts."sub.zhyi.cc" = {
    locations = {
      "/" = {
        proxyPass = "https://${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS}";
        enableOAuth = true;
        extraConfig = ''
          proxy_ssl_name sub.zhyi.cc;
          proxy_ssl_server_name on;
        '';
      };
      "= /mihomo.yaml" = {
        proxyPass = "https://${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS}";
        extraConfig = ''
          proxy_ssl_name sub.zhyi.cc;
          proxy_ssl_server_name on;
        '';
      };
    };
    sslCertificate = "lets-encrypt-zhyi.cc";
    noIndex.enable = true;
  };

  # Keep high-traffic services on the home ingress. Public low-traffic
  # services enter through jpvm, then cross LTNET to this SNI dispatcher.
  services.nginx.streamConfig = ''
    map "$remote_addr:$ssl_preread_server_name" $lan_https_upstream {
      ~^${lib.escapeRegex LT.hosts.jpvm.public.IPv4}:(homepage\.ml-home-vm\.zhyi\.cc|ha\.zhyi\.cc)$ ${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS};
      ~:homepage\.ml-home-vm\.zhyi\.cc$ 127.0.0.1:1;
      ~:n8n\.zhyi\.xin$ ${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS};
      ~:.*\.ml-home-vm\.zhyi\.cc$ ${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS};
      default 127.0.0.1:${LT.portStr.HTTPS};
    }

    map $ssl_preread_server_name $ltnet_https_upstream {
      ~^zhyi\.xin$ ${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS};
      ~^(ai|bitwarden|filebox|index|index-helper|sso)\.zhyi\.xin$ ${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS};
      ~^n8n\.zhyi\.xin$ ${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS};
      ~^ha\.zhyi\.cc$ ${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS};
      ~(^|\.)ml-home-vm\.zhyi\.cc$ ${LT.hosts.ml-home-vm.interconnect.IPv4}:${LT.portStr.HTTPS};
      default 127.0.0.1:${LT.portStr.HTTPS};
    }

    server {
      listen ${LT.this.interconnect.IPv4}:443;
      proxy_pass $lan_https_upstream;
      ssl_preread on;
    }

    server {
      listen ${LT.this.ltnet.IPv4}:443;
      proxy_pass $ltnet_https_upstream;
      ssl_preread on;
    }
  '';

  virtualisation.oci-containers.containers.byparr.ports = [
    "${LT.this.ltnet.IPv4}:${LT.portStr.FlareSolverr}:8191"
  ];
  systemd.services.flaresolverr = lib.mkIf config.services.flaresolverr.enable {
    environment.HOST = lib.mkForce LT.this.ltnet.IPv4;
  };

  # Keep the author's account automation units available, but leave them
  # dormant until this deployment has its own account-specific configuration.
  systemd.services.email-oauth2-proxy.unitConfig.ConditionPathExists =
    "${inputs.secrets}/imapfilter/emailproxy.config";
  systemd.services.imapfilter-outlook.unitConfig.ConditionPathExists =
    "${inputs.secrets}/imapfilter/outlook.lua";
  systemd.services.imapfilter-gmail.unitConfig.ConditionPathExists =
    "${inputs.secrets}/imapfilter/gmail.lua";
  systemd.services.imapfilter-lantian.unitConfig.ConditionPathExists =
    "${inputs.secrets}/imapfilter/lantian.lua";

  systemd.services.tg-bot-cleaner-bot.serviceConfig.ExecCondition = [
    "${pkgs.gnugrep}/bin/grep -qE ^TG_API_ID=.+$ ${config.sops.secrets.tg-bot-cleaner-bot.path}"
    "${pkgs.gnugrep}/bin/grep -qE ^TG_API_HASH=.+$ ${config.sops.secrets.tg-bot-cleaner-bot.path}"
  ];
  systemd.services.cleanup-github-notifications.serviceConfig.ExecCondition =
    "${pkgs.gnugrep}/bin/grep -qE ^GITHUB_TOKEN=.+$ ${config.sops.secrets.cleanup-github-notifications-env.path}";
}
