{
  inputs,
  config,
  lib,
  LT,
  ...
}:
{
  imports = [
    ../../nixos/server.nix

    ./hardware-configuration.nix
    ./ddns-gcore.nix

    ../../nixos/optional-apps/acme
    ../../nixos/optional-apps/attic.nix
    ../../nixos/optional-apps/bepasty.nix
    ../../nixos/optional-apps/bird-lg-go.nix
    ../../nixos/optional-apps/byparr.nix
    ../../nixos/optional-apps/dex.nix
    ../../nixos/optional-apps/flapalerted.nix
    ../../nixos/optional-apps/gitea
    ../../nixos/optional-apps/gitea-actions.nix
    ../../nixos/optional-apps/glauth.nix
    ../../nixos/optional-apps/imapfilter.nix
    ../../nixos/optional-apps/lemmy.nix
    ../../nixos/optional-apps/maddy.nix
    ../../nixos/optional-apps/matrix-synapse
    ../../nixos/optional-apps/miniflux.nix
    ../../nixos/optional-apps/netbox.nix
    ../../nixos/optional-apps/plausible.nix
    ../../nixos/optional-apps/pocket-id.nix
    ../../nixos/optional-apps/pyison
    ../../nixos/optional-apps/quassel.nix
    ../../nixos/optional-apps/radicale.nix
    ../../nixos/optional-apps/rsshub.nix
    ../../nixos/optional-apps/rsync-server-ci.nix
    ../../nixos/optional-apps/syncthing
    ../../nixos/optional-apps/tg-bot-cleaner-bot
    ../../nixos/optional-apps/waline
    ../../nixos/optional-apps/yggdrasil-alfis.nix
    ../../nixos/optional-apps/zerotierone-controller.nix

    ../../nixos/optional-cron-jobs/cleanup-github-notifications
    ../../nixos/optional-cron-jobs/dn42-certificate.nix
    ../../nixos/optional-cron-jobs/radicale-calendar-sync.nix
    ../../nixos/optional-cron-jobs/testssl.nix

    "${inputs.secrets}/nixos-hidden-module/11116c7374949a7a"
    "${inputs.secrets}/nixos-hidden-module/35c68fea6f2bde77"
    "${inputs.secrets}/nixos-hidden-module/c9f6c0c333e73062"
    "${inputs.secrets}/nixos-hidden-module/ca877276fe06bd79"
  ];

  # Temporary LAN deployment path while public TCP/2222 is not forwarded.
  deployment.targetHost = lib.mkForce "192.168.2.188";

  systemd.network.networks.ens18 = {
    matchConfig.Name = "ens18";
    networkConfig = {
      DHCP = "yes";
      IPv6AcceptRA = "yes";
    };
    ipv6AcceptRAConfig.DHCPv6Client = "no";
  };

  # Bootstrap files normally generated by the private ltnet-scripts pipeline.
  # The primary sync server owns these paths; generated content can replace them later.
  systemd.tmpfiles.settings.ltnet-scripts = {
    "/nix/sync-servers/ltnet-scripts/pdns-recursor-conf".d = {
      mode = "0755";
      user = "root";
      group = "root";
    };
    "/nix/sync-servers/ltnet-scripts/pdns-recursor-conf/fwd-dn42-interconnect.lua".f = {
      mode = "0644";
      user = "root";
      group = "root";
    };
    "/nix/sync-servers/ltnet-scripts/pdns-recursor-conf/fwd-dn42-interconnect.yml".f = {
      mode = "0644";
      user = "root";
      group = "root";
    };
  };

  # Public HTTPS is exposed on 8443, while services on the overlay resolve
  # zhyi domains directly to this host and expect the standard HTTPS port.
  services.nginx.streamConfig = ''
    server {
      listen ${LT.this.ltnet.IPv4}:443;
      proxy_pass 127.0.0.1:${LT.portStr.HTTPS};
    }
  '';

  virtualisation.oci-containers.containers.byparr.ports = [
    "${LT.this.ltnet.IPv4}:${LT.portStr.FlareSolverr}:8191"
  ];
  systemd.services.flaresolverr = lib.mkIf config.services.flaresolverr.enable {
    environment.HOST = lib.mkForce LT.this.ltnet.IPv4;
  };
}
