{
  lib,
  LT,
  pkgs,
  ...
}:
{
  imports = [
    ../../nixos/minimal.nix
    ./hardware-configuration.nix
  ];

  # No root password override: users.nix (minimal) sets the unified bcrypt
  # password from the secrets flake for both root and zhyi
  # (users.mutableUsers = false).

  # hardening.nix empties /etc/securetty and adds pam_securetty to login, so
  # root cannot log in on any tty (including ttyS2) by default.  This board has
  # no wired NIC and first bring-up goes through the serial console, so
  # explicitly allow ttyS2.
  environment.etc.securetty.text = lib.mkForce ''
    ttyS2
  '';

  # Taishan Pi has no wired NIC: the only uplink is Wi-Fi via a USB adapter
  # (rtw88_usb, wlan0).  Bring it up with wpa_supplicant + systemd-networkd;
  # the WPA passphrase is plaintext in this first-bring-up image and should
  # move to a sops secret later.
  networking.wireless = {
    enable = true;
    networks."moli-1004-iot".psk = "88888888";
  };

  # The minimal-policies ensure-service-restart assertion requires every
  # enabled systemd service to carry a Restart setting; wpa_supplicant
  # (generated by networking.wireless) does not set one by default.
  systemd.services.wpa_supplicant.serviceConfig.Restart = "always";

  # ssh-harden.nix points sshd at /nix/persistent/etc/ssh host keys, but the
  # fresh sdImage only creates the directory.  Ensure the keys exist before
  # sshd starts, otherwise the only way into a first boot is the serial console.
  systemd.services.taishanpi-ssh-host-keys = {
    description = "Generate persistent SSH host keys if missing";
    wantedBy = [ "multi-user.target" ];
    before = [ "sshd.service" ];
    after = [ "nix.mount" ];
    requires = [ "nix.mount" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    path = [ pkgs.openssh ];
    script = ''
      install -d -m 700 /nix/persistent/etc/ssh
      if [ ! -f /nix/persistent/etc/ssh/ssh_host_ed25519_key ]; then
        ssh-keygen -q -t ed25519 -N "" -C "" \
          -f /nix/persistent/etc/ssh/ssh_host_ed25519_key
      fi
      if [ ! -f /nix/persistent/etc/ssh/ssh_host_rsa_key ]; then
        ssh-keygen -q -t rsa -b 4096 -N "" -C "" \
          -f /nix/persistent/etc/ssh/ssh_host_rsa_key
      fi
    '';
  };

  # systemd-networkd owns wlan0 addressing (DHCP); wpa_supplicant owns the
  # association.  The minimal profile already enables systemd-networkd.
  systemd.network.networks."10-taishanpi-wlan" = {
    matchConfig.Name = "wlan0";
    networkConfig = {
      DHCP = "ipv4";
      IPv6AcceptRA = true;
    };
  };

  networking.networkmanager.enable = lib.mkForce false;

  # The installed board has 2 GiB RAM. zram provides a small safety margin for
  # NixOS activation without turning this low-power board into a build worker.
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
  };

  # MIPI panel present on this host; the DSI overlay is applied by the
  # taishanpi hardware module.  zramSwap is already enabled by the minimal
  # hardening profile (zstd, 50%), so it is not redefined here.
}
