{
  lib,
  nixpkgsPath,
  ...
}:
# Radxa Dragon Q8B official kernel.  Same radxa/kernel repo as the Armbian
# vendor kernel, but pinned to the commit referenced by the radxa-pkg/
# linux-qcom rsdk packaging repo's submodule, and using the official
# radxa_qcom_7_0_defconfig instead of Armbian's vendored config.
#
# Key advantages over the Armbian vendor config:
#   - CONFIG_IPV6 defaults to y (built-in) → CONFIG_MPTCP_IPV6 auto-enabled
#     → nginx "listen [::]:80 multipath" works
#   - CONFIG_BTRFS_FS=y (built-in) → no btrfs.ko needed in initrd
#   - CONFIG_EFIVAR_FS=y (built-in)
#   - No CONFIG_DEBUG_INFO_BTF (avoids pahole segfault)
let
  crossPkgs = import nixpkgsPath {
    localSystem = "x86_64-linux";
    crossSystem = lib.systems.examples.aarch64-multiplatform;
    config = { };
    overlays = [ ];
  };

  crossStdenv = crossPkgs.gcc14Stdenv;

  modDirVersion = "7.0.11";

  # Board-specific and NixOS-required options not in the Radxa defconfig.
  extraConfigFragment = crossPkgs.writeText "extra.config" ''
    CONFIG_TC956X_PCI=m
    CONFIG_DWMAC_TC956X=m
    CONFIG_GPIO_TC956X=m
    CONFIG_USB_R8152=m
    CONFIG_ARCH_MMAP_RND_BITS_MAX=33
    CONFIG_ARCH_MMAP_RND_BITS_MIN=18
    CONFIG_ARCH_MMAP_RND_COMPAT_BITS_MAX=16
    CONFIG_ARCH_MMAP_RND_COMPAT_BITS_MIN=11
  '';
in
(crossPkgs.linuxManualConfig {
  stdenv = crossStdenv;
  target = "vmlinuz.efi";
  inherit modDirVersion;
  version = "${modDirVersion}-radxa";
  extraMeta.branch = "linux-7.0.11";
  src = crossPkgs.fetchFromGitHub {
    owner = "radxa";
    repo = "kernel";
    # Pinned to the commit referenced by radxa-pkg/linux-qcom submodule
    # (2026-08-18), the official Radxa kernel for SC8280XP boards.
    rev = "f87cd1e7a6cf9e164ef1a34c846312f9055e3f29";
    hash = lib.fakeHash;
  };
  # Stub configfile — actual .config is generated by `make radxa_qcom_7_0_defconfig`
  # in the overridden configurePhase below.
  configfile = crossPkgs.writeText "stub.config" "";
  config = {
    BTRFS_FS = "y";
    EFIVAR_FS = "y";
    DRM_MSM = "y";
    MPTCP = "y";
    MPTCP_IPV6 = "y";
    STMMAC_ETH = "m";
    BLK_DEV_NVME = "y";
    MMC_SDHCI_MSM = "y";
    QCA808X_PHY = "y";
  };
  kernelPatches = [ ];
  features = {
    efiBootStub = true;
  };
}).overrideAttrs (old: {
  requiredSystemFeatures = (old.requiredSystemFeatures or [ ]) ++ [ "aarch64-cross" ];
  name = "k";
  preConfigure = ''
    export buildRoot="$(pwd)/build"
    mkdir -p "$buildRoot"

    # Expand the official Radxa defconfig
    make O="$buildRoot" radxa_qcom_7_0_defconfig

    # Append board-specific / NixOS-required config, then re-expand
    cat ${extraConfigFragment} >> "$buildRoot/.config"
    make O="$buildRoot" olddefconfig
  '';
  # Replace `make oldconfig` with a no-op since preConfigure already produced
  # a complete .config via olddefconfig.  oldconfig would prompt on EOF.
  configurePhase = builtins.replaceStrings
    [
      ''      make "''${makeFlags[@]}" oldconfig''
    ]
    [
      ''      true''
    ]
    (old.configurePhase or "");
})