{
  lib,
  nixpkgsPath,
  ...
}:
# Radxa Dragon Q8B official kernel.  Source: github.com/radxa/kernel pinned to
# the commit referenced by radxa-pkg/linux-qcom's submodule (2026-08-18).
# The .config was generated by:
#   make ARCH=arm64 radxa_qcom_7_0_defconfig
#   # append TC956x/R8152/MMAP/AMDGPU/DEBUG_INFO overrides
#   make ARCH=arm64 olddefconfig
#   # sed to force DEBUG_INFO_NONE, then olddefconfig again
# and vendored here as sc8280xp_radxa_config + sc8280xp_radxa_config.nix.
#
# Key advantages over the previous Armbian vendor config:
#   CONFIG_IPV6=y (built-in) → CONFIG_MPTCP_IPV6=y (nginx listen [::]:80 multipath)
#   CONFIG_BTRFS_FS=y (built-in) → no btrfs.ko needed in initrd
#   CONFIG_EFIVAR_FS=y, CONFIG_DEBUG_INFO_NONE=y (no pahole/DWARF5 GCC segfault)
let
  crossPkgs = import nixpkgsPath {
    localSystem = "x86_64-linux";
    crossSystem = lib.systems.examples.aarch64-multiplatform;
    config = { };
    overlays = [ ];
  };

  crossStdenv = crossPkgs.gcc14Stdenv;

  modDirVersion = "7.0.11";

  radxaKernelConfig = ./sc8280xp_radxa_config;
  radxaKernelConfigOptions = import ./sc8280xp_radxa_config.nix;
in
(crossPkgs.linuxManualConfig {
  stdenv = crossStdenv;
  target = "vmlinuz.efi";
  inherit modDirVersion;
  version = "${modDirVersion}-radxa";
  extraMeta.branch = "linux-7.0.11";
  src = crossPkgs.fetchFromGitHub {
    owner = "radxa";
    repo = "kernel";
    rev = "f87cd1e7a6cf9e164ef1a34c846312f9055e3f29";
    hash = "sha256-e6Ic4NJ1H0xLbyezDAvqCFpRg7F9AaQpXZiFpBW+Dmw=";
  };
  configfile = radxaKernelConfig;
  config = radxaKernelConfigOptions;
  kernelPatches = [ ];
  features = {
    efiBootStub = true;
  };
}).overrideAttrs (old: {
  requiredSystemFeatures = (old.requiredSystemFeatures or [ ]) ++ [ "aarch64-cross" ];
  name = "k";
  configurePhase = builtins.replaceStrings
    [
      ''      make "''${makeFlags[@]}" oldconfig''
    ]
    [
      ''      make "''${makeFlags[@]}" olddefconfig && make "''${makeFlags[@]}" oldconfig''
    ]
    (old.configurePhase or "");
})